export default {
  // bottom
  HOME_SCREEN: 'HOME_SCREEN',
  EVENT_SCREEN: 'EVENT_SCREEN',
  UTILITY_SCREEN: 'UTILITY_SCREEN',
  MEMBER_SCREEN: 'MEMBER_SCREEN',

  //root main
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',

  //auth
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  FORGET_PASSWORD_SCREEN: 'FORGET_PASSWORD_SCREEN',

  //common
};
